spring:
  profiles:
    active: development
  aop:
    proxy-target-class: false
  jpa:
    hibernate:
      ddl-auto: update  # 自动创建/更新表结构
    show-sql: true      # 显示SQL语句（可选）

##############################################
#
# thymeleaf静态资源配置
#
##############################################
# 默认路径
spring.thymeleaf.prefix: classpath:/templates/
# 后缀
spring.thymeleaf.suffix: .html
# 模板格式
spring.thymeleaf.mode: HTML5
spring.thymeleaf.encoding: UTF-8
debug: true
